// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credential_profiles.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredentialProfile = `-- name: CreateCredentialProfile :one
INSERT INTO credential_profiles (
    id,
    type,
    account_id,
    enabled,
    email,
    expired,
    last_refresh_at,
    encrypted_profile,
    created_at,
    modified_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    NOW(),
    NOW()
)
RETURNING
    id,
    type,
    account_id,
    enabled,
    email,
    expired,
    last_refresh_at,
    encrypted_profile,
    created_at,
    modified_at
`

type CreateCredentialProfileParams struct {
	ID               string             `json:"id"`
	Type             string             `json:"type"`
	AccountID        string             `json:"account_id"`
	Enabled          bool               `json:"enabled"`
	Email            string             `json:"email"`
	Expired          pgtype.Timestamptz `json:"expired"`
	LastRefreshAt    pgtype.Timestamptz `json:"last_refresh_at"`
	EncryptedProfile string             `json:"encrypted_profile"`
}

func (q *Queries) CreateCredentialProfile(ctx context.Context, arg CreateCredentialProfileParams) (CredentialProfile, error) {
	row := q.db.QueryRow(ctx, createCredentialProfile,
		arg.ID,
		arg.Type,
		arg.AccountID,
		arg.Enabled,
		arg.Email,
		arg.Expired,
		arg.LastRefreshAt,
		arg.EncryptedProfile,
	)
	var i CredentialProfile
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AccountID,
		&i.Enabled,
		&i.Email,
		&i.Expired,
		&i.LastRefreshAt,
		&i.EncryptedProfile,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listCredentialProfiles = `-- name: ListCredentialProfiles :many
SELECT
    id,
    type,
    account_id,
    enabled,
    email,
    expired,
    last_refresh_at,
    encrypted_profile,
    created_at,
    modified_at
FROM credential_profiles
ORDER BY modified_at DESC
`

func (q *Queries) ListCredentialProfiles(ctx context.Context) ([]CredentialProfile, error) {
	rows, err := q.db.Query(ctx, listCredentialProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CredentialProfile{}
	for rows.Next() {
		var i CredentialProfile
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.AccountID,
			&i.Enabled,
			&i.Email,
			&i.Expired,
			&i.LastRefreshAt,
			&i.EncryptedProfile,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredentialProfile = `-- name: UpdateCredentialProfile :one
UPDATE credential_profiles
SET
    type = $2,
    account_id = $3,
    enabled = $4,
    email = $5,
    expired = $6,
    last_refresh_at = $7,
    encrypted_profile = $8,
    modified_at = NOW()
WHERE id = $1
RETURNING
    id,
    type,
    account_id,
    enabled,
    email,
    expired,
    last_refresh_at,
    encrypted_profile,
    created_at,
    modified_at
`

type UpdateCredentialProfileParams struct {
	ID               string             `json:"id"`
	Type             string             `json:"type"`
	AccountID        string             `json:"account_id"`
	Enabled          bool               `json:"enabled"`
	Email            string             `json:"email"`
	Expired          pgtype.Timestamptz `json:"expired"`
	LastRefreshAt    pgtype.Timestamptz `json:"last_refresh_at"`
	EncryptedProfile string             `json:"encrypted_profile"`
}

func (q *Queries) UpdateCredentialProfile(ctx context.Context, arg UpdateCredentialProfileParams) (CredentialProfile, error) {
	row := q.db.QueryRow(ctx, updateCredentialProfile,
		arg.ID,
		arg.Type,
		arg.AccountID,
		arg.Enabled,
		arg.Email,
		arg.Expired,
		arg.LastRefreshAt,
		arg.EncryptedProfile,
	)
	var i CredentialProfile
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AccountID,
		&i.Enabled,
		&i.Email,
		&i.Expired,
		&i.LastRefreshAt,
		&i.EncryptedProfile,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const upsertCredentialProfileByTypeAccount = `-- name: UpsertCredentialProfileByTypeAccount :one
INSERT INTO credential_profiles (
    type,
    account_id,
    enabled,
    email,
    expired,
    last_refresh_at,
    encrypted_profile,
    created_at,
    modified_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    NOW(),
    NOW()
)
ON CONFLICT (type, account_id)
DO UPDATE SET
    enabled = EXCLUDED.enabled,
    email = EXCLUDED.email,
    expired = EXCLUDED.expired,
    last_refresh_at = EXCLUDED.last_refresh_at,
    encrypted_profile = EXCLUDED.encrypted_profile,
    modified_at = NOW()
RETURNING
    id,
    type,
    account_id,
    enabled,
    email,
    expired,
    last_refresh_at,
    encrypted_profile,
    created_at,
    modified_at
`

type UpsertCredentialProfileByTypeAccountParams struct {
	Type             string             `json:"type"`
	AccountID        string             `json:"account_id"`
	Enabled          bool               `json:"enabled"`
	Email            string             `json:"email"`
	Expired          pgtype.Timestamptz `json:"expired"`
	LastRefreshAt    pgtype.Timestamptz `json:"last_refresh_at"`
	EncryptedProfile string             `json:"encrypted_profile"`
}

func (q *Queries) UpsertCredentialProfileByTypeAccount(ctx context.Context, arg UpsertCredentialProfileByTypeAccountParams) (CredentialProfile, error) {
	row := q.db.QueryRow(ctx, upsertCredentialProfileByTypeAccount,
		arg.Type,
		arg.AccountID,
		arg.Enabled,
		arg.Email,
		arg.Expired,
		arg.LastRefreshAt,
		arg.EncryptedProfile,
	)
	var i CredentialProfile
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AccountID,
		&i.Enabled,
		&i.Email,
		&i.Expired,
		&i.LastRefreshAt,
		&i.EncryptedProfile,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
