// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CredentialProfile struct {
	ID               string             `json:"id"`
	Type             string             `json:"type"`
	AccountID        string             `json:"account_id"`
	Enabled          bool               `json:"enabled"`
	Email            string             `json:"email"`
	Expired          pgtype.Timestamptz `json:"expired"`
	LastRefreshAt    pgtype.Timestamptz `json:"last_refresh_at"`
	EncryptedProfile string             `json:"encrypted_profile"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ModifiedAt       pgtype.Timestamptz `json:"modified_at"`
}
