// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"
)

type Querier interface {
	CreateCredentialProfile(ctx context.Context, arg CreateCredentialProfileParams) (CredentialProfile, error)
	ListCredentialProfiles(ctx context.Context) ([]CredentialProfile, error)
	UpdateCredentialProfile(ctx context.Context, arg UpdateCredentialProfileParams) (CredentialProfile, error)
	UpsertCredentialProfileByTypeAccount(ctx context.Context, arg UpsertCredentialProfileByTypeAccountParams) (CredentialProfile, error)
}

var _ Querier = (*Queries)(nil)
