// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage_audit_logs.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateUsageByCredential = `-- name: AggregateUsageByCredential :many
SELECT
    credential_id,
    credential_type,
    credential_account_id,
    COUNT(*) as request_count,
    SUM(prompt_tokens) as total_prompt_tokens,
    SUM(cached_tokens) as total_cached_tokens,
    SUM(completion_tokens) as total_completion_tokens,
    SUM(total_tokens) as total_tokens,
    SUM(total_price_micros) as total_price_micros,
    COUNT(*) FILTER (WHERE status = 'done') as success_count,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_count,
    COUNT(*) FILTER (WHERE status = 'canceled') as canceled_count
FROM usage_audit_logs
WHERE created_at >= $1::timestamptz
  AND created_at < $2::timestamptz
GROUP BY credential_id, credential_type, credential_account_id
ORDER BY request_count DESC
`

type AggregateUsageByCredentialParams struct {
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type AggregateUsageByCredentialRow struct {
	CredentialID          string `json:"credential_id"`
	CredentialType        string `json:"credential_type"`
	CredentialAccountID   string `json:"credential_account_id"`
	RequestCount          int64  `json:"request_count"`
	TotalPromptTokens     int64  `json:"total_prompt_tokens"`
	TotalCachedTokens     int64  `json:"total_cached_tokens"`
	TotalCompletionTokens int64  `json:"total_completion_tokens"`
	TotalTokens           int64  `json:"total_tokens"`
	TotalPriceMicros      int64  `json:"total_price_micros"`
	SuccessCount          int64  `json:"success_count"`
	FailedCount           int64  `json:"failed_count"`
	CanceledCount         int64  `json:"canceled_count"`
}

func (q *Queries) AggregateUsageByCredential(ctx context.Context, arg AggregateUsageByCredentialParams) ([]AggregateUsageByCredentialRow, error) {
	rows, err := q.db.Query(ctx, aggregateUsageByCredential, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateUsageByCredentialRow{}
	for rows.Next() {
		var i AggregateUsageByCredentialRow
		if err := rows.Scan(
			&i.CredentialID,
			&i.CredentialType,
			&i.CredentialAccountID,
			&i.RequestCount,
			&i.TotalPromptTokens,
			&i.TotalCachedTokens,
			&i.TotalCompletionTokens,
			&i.TotalTokens,
			&i.TotalPriceMicros,
			&i.SuccessCount,
			&i.FailedCount,
			&i.CanceledCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateUsageByModel = `-- name: AggregateUsageByModel :many
SELECT
    model,
    COUNT(*) as request_count,
    SUM(prompt_tokens) as total_prompt_tokens,
    SUM(cached_tokens) as total_cached_tokens,
    SUM(completion_tokens) as total_completion_tokens,
    SUM(total_tokens) as total_tokens,
    SUM(total_price_micros) as total_price_micros,
    COUNT(*) FILTER (WHERE status = 'done') as success_count,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_count,
    COUNT(*) FILTER (WHERE status = 'canceled') as canceled_count
FROM usage_audit_logs
WHERE created_at >= $1::timestamptz
  AND created_at < $2::timestamptz
GROUP BY model
ORDER BY request_count DESC
`

type AggregateUsageByModelParams struct {
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type AggregateUsageByModelRow struct {
	Model                 string `json:"model"`
	RequestCount          int64  `json:"request_count"`
	TotalPromptTokens     int64  `json:"total_prompt_tokens"`
	TotalCachedTokens     int64  `json:"total_cached_tokens"`
	TotalCompletionTokens int64  `json:"total_completion_tokens"`
	TotalTokens           int64  `json:"total_tokens"`
	TotalPriceMicros      int64  `json:"total_price_micros"`
	SuccessCount          int64  `json:"success_count"`
	FailedCount           int64  `json:"failed_count"`
	CanceledCount         int64  `json:"canceled_count"`
}

func (q *Queries) AggregateUsageByModel(ctx context.Context, arg AggregateUsageByModelParams) ([]AggregateUsageByModelRow, error) {
	rows, err := q.db.Query(ctx, aggregateUsageByModel, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateUsageByModelRow{}
	for rows.Next() {
		var i AggregateUsageByModelRow
		if err := rows.Scan(
			&i.Model,
			&i.RequestCount,
			&i.TotalPromptTokens,
			&i.TotalCachedTokens,
			&i.TotalCompletionTokens,
			&i.TotalTokens,
			&i.TotalPriceMicros,
			&i.SuccessCount,
			&i.FailedCount,
			&i.CanceledCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateUsageDaily = `-- name: AggregateUsageDaily :many
SELECT
    date_trunc('day', created_at) as day,
    COUNT(*) as request_count,
    SUM(total_tokens) as total_tokens,
    SUM(total_price_micros) as total_price_micros,
    COUNT(*) FILTER (WHERE status = 'done') as success_count,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_count
FROM usage_audit_logs
WHERE created_at >= $1::timestamptz
  AND created_at < $2::timestamptz
GROUP BY date_trunc('day', created_at)
ORDER BY day
`

type AggregateUsageDailyParams struct {
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type AggregateUsageDailyRow struct {
	Day              pgtype.Interval `json:"day"`
	RequestCount     int64           `json:"request_count"`
	TotalTokens      int64           `json:"total_tokens"`
	TotalPriceMicros int64           `json:"total_price_micros"`
	SuccessCount     int64           `json:"success_count"`
	FailedCount      int64           `json:"failed_count"`
}

func (q *Queries) AggregateUsageDaily(ctx context.Context, arg AggregateUsageDailyParams) ([]AggregateUsageDailyRow, error) {
	rows, err := q.db.Query(ctx, aggregateUsageDaily, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateUsageDailyRow{}
	for rows.Next() {
		var i AggregateUsageDailyRow
		if err := rows.Scan(
			&i.Day,
			&i.RequestCount,
			&i.TotalTokens,
			&i.TotalPriceMicros,
			&i.SuccessCount,
			&i.FailedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateUsageHourly = `-- name: AggregateUsageHourly :many
SELECT
    date_trunc('hour', created_at) as hour,
    COUNT(*) as request_count,
    SUM(total_tokens) as total_tokens,
    SUM(total_price_micros) as total_price_micros,
    COUNT(*) FILTER (WHERE status = 'done') as success_count,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_count
FROM usage_audit_logs
WHERE created_at >= $1::timestamptz
  AND created_at < $2::timestamptz
GROUP BY date_trunc('hour', created_at)
ORDER BY hour
`

type AggregateUsageHourlyParams struct {
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type AggregateUsageHourlyRow struct {
	Hour             pgtype.Interval `json:"hour"`
	RequestCount     int64           `json:"request_count"`
	TotalTokens      int64           `json:"total_tokens"`
	TotalPriceMicros int64           `json:"total_price_micros"`
	SuccessCount     int64           `json:"success_count"`
	FailedCount      int64           `json:"failed_count"`
}

func (q *Queries) AggregateUsageHourly(ctx context.Context, arg AggregateUsageHourlyParams) ([]AggregateUsageHourlyRow, error) {
	rows, err := q.db.Query(ctx, aggregateUsageHourly, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateUsageHourlyRow{}
	for rows.Next() {
		var i AggregateUsageHourlyRow
		if err := rows.Scan(
			&i.Hour,
			&i.RequestCount,
			&i.TotalTokens,
			&i.TotalPriceMicros,
			&i.SuccessCount,
			&i.FailedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUsageAuditLogs = `-- name: CountUsageAuditLogs :one
SELECT COUNT(*)
FROM usage_audit_logs
WHERE created_at >= $1::timestamptz
  AND created_at < $2::timestamptz
`

type CountUsageAuditLogsParams struct {
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) CountUsageAuditLogs(ctx context.Context, arg CountUsageAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsageAuditLogs, arg.StartTime, arg.EndTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUsageAuditLog = `-- name: CreateUsageAuditLog :one
INSERT INTO usage_audit_logs (
    id,
    request_id,
    model,
    provider,
    credential_id,
    credential_type,
    credential_account_id,
    prompt_tokens,
    cached_tokens,
    completion_tokens,
    total_tokens,
    input_price_micros,
    output_price_micros,
    total_price_micros,
    status,
    error_message,
    started_at,
    completed_at,
    duration_ms,
    stream,
    created_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, NOW()
)
RETURNING id, request_id, model, provider, credential_id, credential_type, credential_account_id, prompt_tokens, completion_tokens, total_tokens, input_price_micros, output_price_micros, total_price_micros, status, error_message, started_at, completed_at, duration_ms, stream, created_at, cached_tokens
`

type CreateUsageAuditLogParams struct {
	ID                  string             `json:"id"`
	RequestID           string             `json:"request_id"`
	Model               string             `json:"model"`
	Provider            string             `json:"provider"`
	CredentialID        string             `json:"credential_id"`
	CredentialType      string             `json:"credential_type"`
	CredentialAccountID string             `json:"credential_account_id"`
	PromptTokens        int32              `json:"prompt_tokens"`
	CachedTokens        int32              `json:"cached_tokens"`
	CompletionTokens    int32              `json:"completion_tokens"`
	TotalTokens         int32              `json:"total_tokens"`
	InputPriceMicros    int64              `json:"input_price_micros"`
	OutputPriceMicros   int64              `json:"output_price_micros"`
	TotalPriceMicros    int64              `json:"total_price_micros"`
	Status              string             `json:"status"`
	ErrorMessage        pgtype.Text        `json:"error_message"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	DurationMs          int32              `json:"duration_ms"`
	Stream              bool               `json:"stream"`
}

func (q *Queries) CreateUsageAuditLog(ctx context.Context, arg CreateUsageAuditLogParams) (UsageAuditLog, error) {
	row := q.db.QueryRow(ctx, createUsageAuditLog,
		arg.ID,
		arg.RequestID,
		arg.Model,
		arg.Provider,
		arg.CredentialID,
		arg.CredentialType,
		arg.CredentialAccountID,
		arg.PromptTokens,
		arg.CachedTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.InputPriceMicros,
		arg.OutputPriceMicros,
		arg.TotalPriceMicros,
		arg.Status,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
		arg.DurationMs,
		arg.Stream,
	)
	var i UsageAuditLog
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Model,
		&i.Provider,
		&i.CredentialID,
		&i.CredentialType,
		&i.CredentialAccountID,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.InputPriceMicros,
		&i.OutputPriceMicros,
		&i.TotalPriceMicros,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.Stream,
		&i.CreatedAt,
		&i.CachedTokens,
	)
	return i, err
}

const deleteUsageAuditLogsBefore = `-- name: DeleteUsageAuditLogsBefore :execrows
DELETE FROM usage_audit_logs
WHERE created_at < $1
`

func (q *Queries) DeleteUsageAuditLogsBefore(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUsageAuditLogsBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUsageAuditLogByRequestID = `-- name: GetUsageAuditLogByRequestID :one
SELECT id, request_id, model, provider, credential_id, credential_type, credential_account_id, prompt_tokens, completion_tokens, total_tokens, input_price_micros, output_price_micros, total_price_micros, status, error_message, started_at, completed_at, duration_ms, stream, created_at, cached_tokens
FROM usage_audit_logs
WHERE request_id = $1
LIMIT 1
`

func (q *Queries) GetUsageAuditLogByRequestID(ctx context.Context, requestID string) (UsageAuditLog, error) {
	row := q.db.QueryRow(ctx, getUsageAuditLogByRequestID, requestID)
	var i UsageAuditLog
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Model,
		&i.Provider,
		&i.CredentialID,
		&i.CredentialType,
		&i.CredentialAccountID,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.InputPriceMicros,
		&i.OutputPriceMicros,
		&i.TotalPriceMicros,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.Stream,
		&i.CreatedAt,
		&i.CachedTokens,
	)
	return i, err
}

const getUsageOverview = `-- name: GetUsageOverview :one
SELECT
    COUNT(*) as total_requests,
    COALESCE(SUM(prompt_tokens), 0) as total_prompt_tokens,
    COALESCE(SUM(cached_tokens), 0) as total_cached_tokens,
    COALESCE(SUM(completion_tokens), 0) as total_completion_tokens,
    COALESCE(SUM(total_tokens), 0) as total_tokens,
    COALESCE(SUM(total_price_micros), 0) as total_price_micros,
    COUNT(*) FILTER (WHERE status = 'done') as success_count,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_count,
    COUNT(*) FILTER (WHERE status = 'canceled') as canceled_count,
    COALESCE(AVG(duration_ms), 0) as avg_duration_ms
FROM usage_audit_logs
WHERE created_at >= $1::timestamptz
  AND created_at < $2::timestamptz
`

type GetUsageOverviewParams struct {
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type GetUsageOverviewRow struct {
	TotalRequests         int64       `json:"total_requests"`
	TotalPromptTokens     interface{} `json:"total_prompt_tokens"`
	TotalCachedTokens     interface{} `json:"total_cached_tokens"`
	TotalCompletionTokens interface{} `json:"total_completion_tokens"`
	TotalTokens           interface{} `json:"total_tokens"`
	TotalPriceMicros      interface{} `json:"total_price_micros"`
	SuccessCount          int64       `json:"success_count"`
	FailedCount           int64       `json:"failed_count"`
	CanceledCount         int64       `json:"canceled_count"`
	AvgDurationMs         interface{} `json:"avg_duration_ms"`
}

func (q *Queries) GetUsageOverview(ctx context.Context, arg GetUsageOverviewParams) (GetUsageOverviewRow, error) {
	row := q.db.QueryRow(ctx, getUsageOverview, arg.StartTime, arg.EndTime)
	var i GetUsageOverviewRow
	err := row.Scan(
		&i.TotalRequests,
		&i.TotalPromptTokens,
		&i.TotalCachedTokens,
		&i.TotalCompletionTokens,
		&i.TotalTokens,
		&i.TotalPriceMicros,
		&i.SuccessCount,
		&i.FailedCount,
		&i.CanceledCount,
		&i.AvgDurationMs,
	)
	return i, err
}

const listUsageAuditLogs = `-- name: ListUsageAuditLogs :many
SELECT id, request_id, model, provider, credential_id, credential_type, credential_account_id, prompt_tokens, completion_tokens, total_tokens, input_price_micros, output_price_micros, total_price_micros, status, error_message, started_at, completed_at, duration_ms, stream, created_at, cached_tokens
FROM usage_audit_logs
WHERE created_at >= $1::timestamptz
  AND created_at < $2::timestamptz
ORDER BY created_at DESC
LIMIT $4::int
OFFSET $3::int
`

type ListUsageAuditLogsParams struct {
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	OffsetVal int32              `json:"offset_val"`
	LimitVal  int32              `json:"limit_val"`
}

func (q *Queries) ListUsageAuditLogs(ctx context.Context, arg ListUsageAuditLogsParams) ([]UsageAuditLog, error) {
	rows, err := q.db.Query(ctx, listUsageAuditLogs,
		arg.StartTime,
		arg.EndTime,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageAuditLog{}
	for rows.Next() {
		var i UsageAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Model,
			&i.Provider,
			&i.CredentialID,
			&i.CredentialType,
			&i.CredentialAccountID,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.InputPriceMicros,
			&i.OutputPriceMicros,
			&i.TotalPriceMicros,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationMs,
			&i.Stream,
			&i.CreatedAt,
			&i.CachedTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageAuditLogsByCredential = `-- name: ListUsageAuditLogsByCredential :many
SELECT id, request_id, model, provider, credential_id, credential_type, credential_account_id, prompt_tokens, completion_tokens, total_tokens, input_price_micros, output_price_micros, total_price_micros, status, error_message, started_at, completed_at, duration_ms, stream, created_at, cached_tokens
FROM usage_audit_logs
WHERE credential_id = $1
  AND created_at >= $2::timestamptz
  AND created_at < $3::timestamptz
ORDER BY created_at DESC
LIMIT $5::int
OFFSET $4::int
`

type ListUsageAuditLogsByCredentialParams struct {
	CredentialID string             `json:"credential_id"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	EndTime      pgtype.Timestamptz `json:"end_time"`
	OffsetVal    int32              `json:"offset_val"`
	LimitVal     int32              `json:"limit_val"`
}

func (q *Queries) ListUsageAuditLogsByCredential(ctx context.Context, arg ListUsageAuditLogsByCredentialParams) ([]UsageAuditLog, error) {
	rows, err := q.db.Query(ctx, listUsageAuditLogsByCredential,
		arg.CredentialID,
		arg.StartTime,
		arg.EndTime,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageAuditLog{}
	for rows.Next() {
		var i UsageAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Model,
			&i.Provider,
			&i.CredentialID,
			&i.CredentialType,
			&i.CredentialAccountID,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.InputPriceMicros,
			&i.OutputPriceMicros,
			&i.TotalPriceMicros,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationMs,
			&i.Stream,
			&i.CreatedAt,
			&i.CachedTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageAuditLogsByModel = `-- name: ListUsageAuditLogsByModel :many
SELECT id, request_id, model, provider, credential_id, credential_type, credential_account_id, prompt_tokens, completion_tokens, total_tokens, input_price_micros, output_price_micros, total_price_micros, status, error_message, started_at, completed_at, duration_ms, stream, created_at, cached_tokens
FROM usage_audit_logs
WHERE model = $1
  AND created_at >= $2::timestamptz
  AND created_at < $3::timestamptz
ORDER BY created_at DESC
LIMIT $5::int
OFFSET $4::int
`

type ListUsageAuditLogsByModelParams struct {
	Model     string             `json:"model"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	OffsetVal int32              `json:"offset_val"`
	LimitVal  int32              `json:"limit_val"`
}

func (q *Queries) ListUsageAuditLogsByModel(ctx context.Context, arg ListUsageAuditLogsByModelParams) ([]UsageAuditLog, error) {
	rows, err := q.db.Query(ctx, listUsageAuditLogsByModel,
		arg.Model,
		arg.StartTime,
		arg.EndTime,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageAuditLog{}
	for rows.Next() {
		var i UsageAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Model,
			&i.Provider,
			&i.CredentialID,
			&i.CredentialType,
			&i.CredentialAccountID,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.InputPriceMicros,
			&i.OutputPriceMicros,
			&i.TotalPriceMicros,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationMs,
			&i.Stream,
			&i.CreatedAt,
			&i.CachedTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
