package handler

import (
	"crypto/sha256"
	"fmt"
	"net/http"
	"time"

	domaincompletion "github.com/duchoang/llmpool/internal/domain/completion"
	domainollama "github.com/duchoang/llmpool/internal/domain/ollama"
	usecasecompletion "github.com/duchoang/llmpool/internal/usecase/completion"
	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
)

// OllamaCompatVersion is the Ollama version reported to clients.
// Kept high enough so VS Code extensions don't reject the server.
const OllamaCompatVersion = "0.17.6"

// OllamaHandler exposes Ollama-compatible discovery endpoints
// so that VS Code extensions (Continue, etc.) can detect and use LLMPool.
type OllamaHandler struct {
	service usecasecompletion.CompletionService
	logger  *zap.Logger
}

// NewOllamaHandler creates a new Ollama compatibility handler.
func NewOllamaHandler(service usecasecompletion.CompletionService, logger *zap.Logger) *OllamaHandler {
	return &OllamaHandler{
		service: service,
		logger:  logger,
	}
}

// Tags handles GET /api/tags — returns models in Ollama format.
func (h *OllamaHandler) Tags(c *gin.Context) {
	ctx := c.Request.Context()

	h.logger.Debug("ollama tags request")

	resp, err := h.service.ListModels(ctx)
	if err != nil {
		h.logger.Error("list models for ollama tags", zap.Error(err))
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	models := make([]domainollama.ModelInfo, 0, len(resp.Data))
	now := time.Now()

	for _, m := range resp.Data {
		models = append(models, toOllamaModel(m.ID, now))
	}

	c.JSON(http.StatusOK, domainollama.TagsResponse{Models: models})
}

// Version handles GET /api/version — returns an Ollama-compatible version string.
func (h *OllamaHandler) Version(c *gin.Context) {
	c.JSON(http.StatusOK, domainollama.VersionResponse{
		Version: OllamaCompatVersion,
	})
}

// Show handles POST /api/show — returns model metadata in Ollama format.
func (h *OllamaHandler) Show(c *gin.Context) {
	var req domainollama.ShowRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request body: " + err.Error()})
		return
	}

	if req.Model == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "model is required"})
		return
	}

	h.logger.Debug("ollama show request", zap.String("model", req.Model))

	// Verify the model exists in our registry
	ctx := c.Request.Context()
	resp, err := h.service.ListModels(ctx)
	if err != nil {
		h.logger.Error("list models for ollama show", zap.Error(err))
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	if !modelExists(resp.Data, req.Model) {
		c.JSON(http.StatusNotFound, gin.H{"error": fmt.Sprintf("model '%s' not found", req.Model)})
		return
	}

	family := inferFamily(req.Model)
	now := time.Now()

	showResp := domainollama.ShowResponse{
		Modelfile:  fmt.Sprintf("# Modelfile generated by llmpool\nFROM %s", req.Model),
		Parameters: "",
		Template:   "{{ .Prompt }}",
		Details: domainollama.ModelDetails{
			Format:   "api",
			Family:   family,
			Families: []string{family},
		},
		ModelInfo: map[string]any{
			"general.architecture": family,
			"general.name":         req.Model,
			"llmpool.proxy":        true,
		},
		ModifiedAt: now,
	}

	c.JSON(http.StatusOK, showResp)
}

// modelExists checks whether a model ID is present in the models list.
func modelExists(models []domaincompletion.Model, id string) bool {
	for _, m := range models {
		if m.ID == id {
			return true
		}
	}
	return false
}

// toOllamaModel builds a synthetic ModelInfo from a model ID.
// Ollama clients mostly care about name/model; the rest is best-effort metadata.
func toOllamaModel(id string, modifiedAt time.Time) domainollama.ModelInfo {
	family := inferFamily(id)
	digest := fmt.Sprintf("%x", sha256.Sum256([]byte(id)))

	return domainollama.ModelInfo{
		Name:       id,
		Model:      id,
		ModifiedAt: modifiedAt,
		Size:       0,
		Digest:     digest,
		Details: domainollama.ModelDetails{
			Format:   "api",
			Family:   family,
			Families: []string{family},
		},
	}
}

// inferFamily returns a rough family string from the model ID.
func inferFamily(id string) string {
	switch {
	case len(id) >= 3 && id[:3] == "gpt":
		return "gpt"
	case len(id) >= 6 && id[:6] == "claude":
		return "claude"
	case len(id) >= 6 && id[:6] == "gemini":
		return "gemini"
	case len(id) >= 1 && id[:1] == "o":
		return "o-series"
	default:
		return "unknown"
	}
}
